### ISSUE TITLE
IRCELINE network does not yield humidity measurements

### ISSUE THREAD

**Issue by amotl** [hiveeyes/luftdatenpumpe#1]
@wetterfrosch just reported that the IRCELINE network apparently does not yield humidity measurements. This matches the observations on https://map.influencair.be/.

So we are humbly asking the upstream people here: Is there something you could do about improving that situation?

**Comment by opeeters** [comment]
I will check if we can maybe also publish humidity measurements for some of the air quality measuring stations, but currently there is indeed no humidity available via our API.

Maybe one of the opendata services from our meteorological institute could help:
* https://opendata.meteo.be/
* https://opendata.meteo.be/geonetwork/srv/eng/catalog.search#/metadata/RMI_DATASET_ALARO

Maybe the relative humidity layer from the ALARO model (e.g. via WCS: https://opendata.meteo.be/service/alaro/wcs)?

**Comment by amotl** [comment]
That was quick. We will check the resources you pointed out to us. Thanks, Olav!

**Comment by wetterfrosch** [comment]
> Maybe one of the opendata services from our meteorological institute could help:

When diving into *.meteo.be I find two answers:
- via 
> * https://opendata.meteo.be/
and selecting "Automatic Weather Stations" there is data from exactly just two (2) stations.
- via
> * https://opendata.meteo.be/geonetwork/srv/eng/catalog.search#/metadata/RMI_DATASET_ALARO
I get as a best result [something like a "value pixmap"](https://opendata.meteo.be/service/ows?service=WCS&version=2.0.1&request=GetCoverage&CoverageId=alaro__2m_Relative_humidity&format=text/plain&SUBSET=http://www.opengis.net/def/axis/OGC/0/Long(-0.1415255706207,9.2485256906048)&SUBSET=http://www.opengis.net/def/axis/OGC/0/Lat(47.379315679724,53.640688592737)&SUBSET=http://www.opengis.net/def/axis/OGC/0/time(%222019-05-13T12:00:00.000Z%22)). Parsing and transforming this into correct geo-coordinates would be a liitte construction site.

Thus we've been are already working with a "nearest station"-lookup for compensation within our main luftendatapumpen-project, I would wait a bit if some humidtiy data would be available via the IRCELINE/SOS-API, @opeeters.

**Comment by amotl** [comment]
Dear @opeeters,

> I will check if we can maybe also publish humidity measurements for some of the air quality measuring stations

Thank you so much for pushing the humidity data into the SOS service. @wetterfrosch already started building upon them on https://vmm.hiveeyes.org/.

With kind regards,
Andreas.
